name: Comprobaciones del proyecto

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  comprobar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Verificar que existe src/index.html
        run: |
          if [ ! -f "src/index.html" ]; then
            echo "❌ Falta src/index.html"
            exit 1
          fi

          echo "✅ Encontrado src/index.html"

      - name: Mostrar contenido del repositorio
        run: ls -R
