name: Comprobaciones del proyecto

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  comprobar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Verificar que existe index.html
        run: |
          if [ ! -f "index.html" ]; then
            echo "Falta index.html"
            exit 1
          fi

      - name: Mostrar contenido del directorio
        run: ls -R
